import {MovieType} from "../movieType";

export const existingMovies: Array<MovieType> = [
  {name: "10000BC"},
  {name: "12 YEARS ASLAVE"},
  {name: "21 BRIDGES"},
  {name: "21 JUMP STREET"},
  {name: "22 JUMP STREET"},
  {name: "300"},
  {name: "300 2"},
  {name: "7 ZWERGE"},
  {name: "ALIEN"},
  {name: "ALITA"},
  {name: "ALLES STEHT KOPF"},
  {name: "AMERICAN SNIPER"},
  {name: "AN EINEM WUNDERSCHÖNEN SONNTAG"},
  {name: "ANT MAN 1"},
  {name: "ANT MAN 2"},
  {name: "APOCALYPTO"},
  {name: "APOLLO 13"},
  {name: "AQUA MAN"},
  {name: "ARRIVAL"},
  {name: "ASSAISENCE CREED"},
  {name: "AVATAR"},
  {name: "AVENGERS 1"},
  {name: "AVENGERS 2"},
  {name: "AVENGERS 3"},
  {name: "BABY DRIVER"},
  {name: "BANANA JOE"},
  {name: "BATMAN"},
  {name: "BATMAN RETURNS"},
  {name: "BATMAN V SUPERMAN"},
  {name: "BAYWATCH"},
  {name: "BEAUTIFUL BOY"},
  {name: "BLACKKKLANSMEN"},
  {name: "BLACK PANTHER"},
  {name: "BLAIR WITCH PROJECT"},
  {name: "BLUE JAY"},
  {name: "BLUES BROTHERS"},
  {name: "BRUCE ALLMäCHTIG"},
  {name: "BULLYPARADE"},
  {name: "CAPTAIN AMERICA 1"},
  {name: "CAPTAIN AMERICA 2"},
  {name: "CAPTAIN AMERICA 3"},
  {name: "CAPTAIN MARVEL"},
  {name: "CASPER"},
  {name: "CAST AWAY"},
  {name: "CATCH ME IF YOU CAN"},
  {name: "CENTRAL INTELLIGENCE"},
  {name: "CHARLIE UND DIE SCHOKOLADENFABRIK"},
  {name: "CHINATOWN"},
  {name: "CLOCKWORK ORANGE"},
  {name: "CODENAME UNCLE"},
  {name: "CONSTANTINE"},
  {name: "CREED 1"},
  {name: "CREED 2"},
  {name: "DADDYS LITTLE GIRLS"},
  {name: "DARK KNIGHT 1"},
  {name: "DARK KNIGHT 2"},
  {name: "DARK KNIGHT 3"},
  {name: "DAS 5. ELEMENT"},
  {name: "DAS LEBEN DES BRIAN"},
  {name: "DAS VERMäCHTNISS DER TEMPELRITTER"},
  {name: "DAS VERMäCHTNISS DES GEHEIMEN BUNDES"},
  {name: "DEADPOOL 1"},
  {name: "DEADPOOL 2"},
  {name: "DER BAADER MEINHOF KOMPLEX"},
  {name: "DER DIKTATOR"},
  {name: "DER GESTIEFELTE KATER"},
  {name: "DER GLADIATOR"},
  {name: "DER GRINCH"},
  {name: "DER HOBBIT 1"},
  {name: "DER HOBBIT 2"},
  {name: "DER HOBBIT 3"},
  {name: "DER JUNGE IM GESTREIFTEN PYJAMA"},
  {name: "DER KNASTCOACH"},
  {name: "DER LEUCHTTURM"},
  {name: "DER MARSIANER"},
  {name: "DER MEDICUS"},
  {name: "DER RAUSCH"},
  {name: "DER SCHATZ IM SILBERSEE"},
  {name: "DER SCHMALE GRAT"},
  {name: "DER SCHUH DES MANITU"},
  {name: "DER SOLDAT DES JAMES RYAN"},
  {name: "DER UNGLAUBLICHE HULK"},
  {name: "DER VORLESER"},
  {name: "DER WEIßE HAI"},
  {name: "DIE ALTE DAME"},
  {name: "DIE BESTIMMUNG 1"},
  {name: "DIE BESTIMMUNG 2"},
  {name: "DIE BESTIMMUNG 3"},
  {name: "DIE CHRONIKEN VON NARNIA 1"},
  {name: "DIE CHRONIKEN VON NARNIA 2"},
  {name: "DIE CHRONIKEN VON NARNIA 3"},
  {name: "DIE DREI MUSKETIERE"},
  {name: "DIE GEHEIMNISVOLLE REISE ZUM MITTELPUNKT DER ERDE"},
  {name: "DIE LEGENDE DES ZORRO"},
  {name: "DIE LEGENDE VON AANG"},
  {name: "DIE LINKE UND DIE RECHTE HAND DES TEUFELS"},
  {name: "DIE MONSTER AG"},
  {name: "DIE MONSTER UNI"},
  {name: "DER PATE"},
  {name: "DIE UNFASSBAREN 1"},
  {name: "DIE UNFASSBAREN 2"},
  {name: "DIE UNGLAUBLICHEN 1"},
  {name: "DIE UNGLAUBLICHEN 2"},
  {name: "DIE WOLKE"},
  {name: "DJANGO UNCHAINED"},
  {name: "DOCTOR STRANGE"},
  {name: "DOCTOR STRANGE 2"},
  {name: "DUNKIRK"},
  {name: "DWK 1"},
  {name: "DWK 2"},
  {name: "DWK 3"},
  {name: "DWK 4"},
  {name: "DWK 5"},
  {name: "E.T."},
  {name: "EAGLE EYE"},
  {name: "EDGE OF TOMORROW"},
  {name: "EINE WEIHNACHTSGESCHICHTE"},
  {name: "EIN RISKANNTER PLAN"},
  {name: "EINS UND EINS MACHT VIER"},
  {name: "ELI"},
  {name: "ER IST WIEDER DA"},
  {name: "FANTASIC FOUR"},
  {name: "FAST AND FURIOS 1"},
  {name: "FAST AND FURIOS 2"},
  {name: "FAST AND FURIOS 3"},
  {name: "FAST AND FURIOS 4"},
  {name: "FAST AND FURIOS 5"},
  {name: "FAST AND FURIOS 6"},
  {name: "FAST AND FURIOS 7"},
  {name: "FAST AND FURIOS 8"},
  {name: "FAST AND FURIOS 9"},
  {name: "FIGHT CLUB"},
  {name: "FINDET NEMO"},
  {name: "FLUCH DER KARIBIK 1"},
  {name: "FLUCH DER KARIBIK 2"},
  {name: "FLUCH DER KARIBIK 3"},
  {name: "FLUCH DER KARIBIK 4"},
  {name: "FLUCH DER KARIBIK 5"},
  {name: "FORREST GUMP"},
  {name: "FUCK YOU GÖTHE 1"},
  {name: "FUCK YOU GÖTHE 2"},
  {name: "FUCK YOU GÖTHE 3"},
  {name: "FULL METAL JACKET"},
  {name: "GAME NIGHT"},
  {name: "GEMINI MEN"},
  {name: "GET OUT"},
  {name: "GLASS"},
  {name: "GOLD"},
  {name: "GONE GIRL"},
  {name: "GOOD BYE LENIN"},
  {name: "GOODFELLAS"},
  {name: "GRAND BUDAPEST HOTEL"},
  {name: "GRAVITY"},
  {name: "GREAT GATSBY"},
  {name: "GREEN BOOK"},
  {name: "GUARDIONS OF THE GALAXY 1"},
  {name: "GUARDIONS OF THE GALAXY 2"},
  {name: "GUNS AKIMBO"},
  {name: "HAIR"},
  {name: "HALLOWEEN"},
  {name: "HANGOVER"},
  {name: "HARDCORE"},
  {name: "HARD POWDER"},
  {name: "HARRY POTTER 1"},
  {name: "HARRY POTTER 2"},
  {name: "HARRY POTTER 3"},
  {name: "HARRY POTTER 4"},
  {name: "HARRY POTTER 5"},
  {name: "HARRY POTTER 6"},
  {name: "HARRY POTTER 7"},
  {name: "HARRY POTTER 8"},
  {name: "HAWKING"},
  {name: "HEIDI"},
  {name: "HERR DER RINGE 1"},
  {name: "HERR DER RINGE 2"},
  {name: "HERR DER RINGE 3"},
  {name: "HIP HOP HOOD"},
  {name: "HITMAN"},
  {name: "HOUSE IN THE WOODS"},
  {name: "I AM LEGEND"},
  {name: "ICH EINFACH UNVERBESSERLICH 1"},
  {name: "ICH EINFACH UNVERBESSERLICH 2"},
  {name: "ICH EINFACH UNVERBESSERLICH 3"},
  {name: "ILLUMINATI"},
  {name: "IMMER AERGER MIT 40"},
  {name: "INCEPTION"},
  {name: "INCLORIOS BASTERDS"},
  {name: "INDEPENDENCE DAY 1"},
  {name: "INDEPENDENCE DAY 2"},
  {name: "INDIANA JONES 1"},
  {name: "INDIANA JONES 2"},
  {name: "INDIANA JONES 3"},
  {name: "INDIANA JONES 4"},
  {name: "INSIDE JOB"},
  {name: "INTERSTELLAR"},
  {name: "IN TIME"},
  {name: "I ROBOT"},
  {name: "IRON MAN 1"},
  {name: "IRON MAN 2"},
  {name: "IRON MAN 3"},
  {name: "ISI UND OSSI"},
  {name: "JAMES BOND 007 SKYFALL"},
  {name: "JAMES BOND 007 SPECTRE"},
  {name: "JOHN WICK 1"},
  {name: "JOHN WICK 2"},
  {name: "JOHN WICK 3"},
  {name: "JOJO RABBIT"},
  {name: "JOKER"},
  {name: "JONNY ENGLISCH 1"},
  {name: "JONNY ENGLISCH 2"},
  {name: "JONNY ENGLISCH 3"},
  {name: "JUMANJI"},
  {name: "JUMPER"},
  {name: "JUNO"},
  {name: "JURASSIC PARK"},
  {name: "JUSTICE LEAGUE"},
  {name: "KILL BILL"},
  {name: "KILL THE BOSS"},
  {name: "KINGSMEN 1"},
  {name: "KINGSMEN 2"},
  {name: "KOKOWÄH"},
  {name: "KUNG FU PANDA"},
  {name: "KÖNIG DER LöWEN"},
  {name: "LEG DICH NICHT MIT ZOHAN AN"},
  {name: "LISSI UND DER WILDE KAISER"},
  {name: "LOGAN"},
  {name: "LOGAN LUCKY"},
  {name: "LONDON HAS FALLEN"},
  {name: "LONG SHOT"},
  {name: "LUCY"},
  {name: "MADAGASKAR"},
  {name: "MAD MAX"},
  {name: "MAMMA MIA"},
  {name: "MATRIX 1"},
  {name: "MATRIX 2"},
  {name: "MATRIX 3"},
  {name: "MAZE RUNNER 1"},
  {name: "MAZE RUNNER 2"},
  {name: "MAZE RUNNER 3"},
  {name: "MEMENTO"},
  {name: "MEN IN BLACK 1"},
  {name: "MEN IN BLACK 2"},
  {name: "MEN IN BLACK 3"},
  {name: "MEN IN BLACK 4"},
  {name: "MIDNIGHT"},
  {name: "MILE"},
  {name: "MINIONS 1"},
  {name: "MINIONS 2"},
  {name: "MISSION IMPOSSIBLE 1"},
  {name: "MISSION IMPOSSIBLE 2"},
  {name: "MISSION IMPOSSIBLE 3"},
  {name: "MISSION IMPOSSIBLE 4"},
  {name: "MISSION IMPOSSIBLE 5"},
  {name: "MISSION IMPOSSIBLE 6"},
  {name: "MOONRISE KINGDOM"},
  {name: "MORTAL ENGINES"},
  {name: "MR. AND MS SMITH"},
  {name: "MR BEAN MACHT FERIEN"},
  {name: "MY FAIR LADY"},
  {name: "NERVE"},
  {name: "NIGHT IN PARADISE"},
  {name: "NIGHT SCHOOL"},
  {name: "NON STOP"},
  {name: "OLYMPUS HAS FALLEN"},
  {name: "ONCE UPON A TIME IN HOLLYWOOD"},
  {name: "OTTO"},
  {name: "OUR IDIOT BROTHER"},
  {name: "PACIFIC RIM 1"},
  {name: "PACIFIC RIM 2"},
  {name: "PAIN AND GAIN"},
  {name: "PANET DER AFFEN 1"},
  {name: "PANET DER AFFEN 2"},
  {name: "PAPILLION"},
  {name: "PERCY JACKSON"},
  {name: "PER ANHALTER DURCH DIE GALAXIS"},
  {name: "PETS"},
  {name: "PHANTASTISCHE TIERWESEN 1"},
  {name: "PHANTASTISCHE TIERWESEN 2"},
  {name: "PIPI LANGSTRUMPF"},
  {name: "PREDATOR"},
  {name: "PRESTIGE"},
  {name: "PRINCE OF PERSIA"},
  {name: "PRISON BREAK-DER FILM"},
  {name: "PROJECT X"},
  {name: "PROMETHEUS"},
  {name: "PULP FICTION"},
  {name: "PURGE 1"},
  {name: "PURGE 2"},
  {name: "PURGE 3"},
  {name: "PURGE 4"},
  {name: "PURGE 5"},
  {name: "RAIN MAN"},
  {name: "RAMBO 1"},
  {name: "RAMBO 5"},
  {name: "RATATOUI"},
  {name: "READY PLAYER ONE"},
  {name: "REC 1"},
  {name: "REC 2"},
  {name: "RED SPARROW"},
  {name: "RELICS"},
  {name: "ROBIN HOOD"},
  {name: "ROBIN HOOD"},
  {name: "ROCKY 1"},
  {name: "ROCKY 2"},
  {name: "ROCKY 4"},
  {name: "ROGUE ONE"},
  {name: "RUSH"},
  {name: "SAN ANDREAS"},
  {name: "SCARY MOVIE 1"},
  {name: "SCARY MOVIE 2"},
  {name: "SCARY MOVIE 3"},
  {name: "SCARY MOVIE 4"},
  {name: "SCARY MOVIE 5"},
  {name: "SHAZAM"},
  {name: "SHERLOCK HOLMES 1"},
  {name: "SHERLOCK HOLMES 2"},
  {name: "SHINING"},
  {name: "SHOUTER"},
  {name: "SIMPSONS"},
  {name: "SING"},
  {name: "SINISTER 1-3"},
  {name: "SISSI"},
  {name: "SKYSCRAPER"},
  {name: "SNITCH"},
  {name: "SNOWDEN"},
  {name: "SOURCE CODE"},
  {name: "SPACEWALK"},
  {name: "SPIDER-MAN 1(TOM HOLLAND)"},
  {name: "SPIDER-MAN 2(TOM HOLLAND)"},
  {name: "SPIDER-MAN 3(TOM HOLLAND)"},
  {name: "SPIDERMAN A NEW SPIDERVERSE"},
  {name: "SPIDER MAN 1(TOBEY MCQUIER)"},
  {name: "SPIDER MAN 2(TOBEY MCQUIER)"},
  {name: "SPIDER MAN 3(TOBEY MCQUIER)"},
  {name: "SPLIT"},
  {name: "STAR TREK 1"},
  {name: "STAR TREK 2"},
  {name: "STAR TREK 3"},
  {name: "STAR WARS 1"},
  {name: "STAR WARS 2"},
  {name: "STAR WARS 3"},
  {name: "STAR WARS 4"},
  {name: "STAR WARS 4"},
  {name: "STAR WARS 5"},
  {name: "STAR WARS 6"},
  {name: "STAR WARS 7"},
  {name: "STAR WARS 8"},
  {name: "STAR WARS 9"},
  {name: "STRAIGHT OUTA COMPTON"},
  {name: "SUICIDE SQUAD"},
  {name: "SUPERMAN"},
  {name: "SUPERMAN RETURNS"},
  {name: "TENET"},
  {name: "THE ACCOUNTANT"},
  {name: "THE AMAZING SPIDERMAN"},
  {name: "THE BIG SHORT"},
  {name: "THE BOSS BABY"},
  {name: "THE BOY"},
  {name: "THE BUTLER"},
  {name: "THE CIRCLE"},
  {name: "THE COMMUTER"},
  {name: "THE DEVIL ALL THE TIME"},
  {name: "THE FRENCH DISPATCH"},
  {name: "THE GREAT DICTATOR"},
  {name: "THE HATEFUL EIGHT"},
  {name: "THE HUNT FOR RED OCTOBER"},
  {name: "THE IMMITATION GAME"},
  {name: "THE INTERVIEW"},
  {name: "THE LIGHTHOUSE"},
  {name: "THE LOBSTER"},
  {name: "THE RAILWAY CHILDREN"},
  {name: "THE REVENANT"},
  {name: "THE SOCIAL NETWORK"},
  {name: "THE SHAWSHANK REDEMPTION"},
  {name: "THE SUICIDE SQUAD"},
  {name: "THE WOLF OF WALL STREET"},
  {name: "THOR 1"},
  {name: "THOR 2"},
  {name: "THOR 3"},
  {name: "TINTENHERZ"},
  {name: "TITANIC"},
  {name: "TOTAL RECALL"},
  {name: "TRANSFORMERS 1"},
  {name: "TRANSFORMERS 2"},
  {name: "TRANSFORMERS 3"},
  {name: "TRANSFORMERS 4"},
  {name: "TRANSFORMERS 5"},
  {name: "TRAUMSCHIFF SURPRISE"},
  {name: "TRIBUTE VON PANEM 1"},
  {name: "TRIBUTE VON PANEM 2"},
  {name: "TRIBUTE VON PANEM 3"},
  {name: "TROJA"},
  {name: "TWILIGHT 1"},
  {name: "TWILIGHT 2"},
  {name: "TWILIGHT 3"},
  {name: "UNBREAKABLE"},
  {name: "VALERIAN"},
  {name: "VENOM"},
  {name: "WANTED"},
  {name: "WARCRAFT"},
  {name: "WAR DOGS"},
  {name: "WATCHMEN"},
  {name: "WEST SIDE STORY"},
  {name: "WICKIE UND DIE STARKEN MäNNER"},
  {name: "WINNETOU 1"},
  {name: "WINNETOU 2"},
  {name: "WINNETOU 3"},
  {name: "WIR"},
  {name: "WONDERWOMEN"},
  {name: "WOYZEK"},
  {name: "X-MEN 1"},
  {name: "X-MEN 2"},
  {name: "X-MEN 3"},
  {name: "X-MEN 4"},
  {name: "X-MEN 5"},
  {name: "X-MEN 6"},
  {name: "X-MEN 7"},
  {name: "X-MEN 8"},
  {name: "X-MEN 9"},
  {name: "XXX"},
  {name: "YESTERDAY"},
  {name: "ZACK SNYDERS JUSTICE LEAGUE"},
  {name: "ZIMMER 1408"},
  {name: "ZURüCK IN DIE ZUKUNFT 1"},
  {name: "ZURüCK IN DIE ZUKUNFT 2"},
  {name: "ZURüCK IN DIE ZUKUNFT 3"},
  {name: "ZWEIOHRKÜCKEN"},
  {name: "DAS SCHWEIGEN DER LÄMMER"},
  {name: "GOODFELLAS"}
]
